### Create a new User

POST  http://Localhost:3000/api/user/signUp
Content-Type: application/json

{
    "username": "Ivygon",
    "password": "Ivygon",
    "email": "mochniyivwdwn@gmail"
}

### Get user information

GET http://Localhost:3000/api/user/search/IvanMoch

### modify user information

PATCH http://Localhost:3000/api/user/IvanMoch


### log user

POST http://Localhost:3000/api/user/logIn
Content-Type: application/json

{
    "username" : "IvanMoch",
    "password" : "IvanMoch"
}

### log out user
GET http://localhost:3000/api/user/logOut