### Create a new User

POST  http://Localhost:3000/api/user/signUp
Content-Type: application/json


    {
    "username": "BobM",
    "password": "securePass1",
    "email": "bobm@example.com"
    }

### Get user information

GET http://Localhost:3000/api/user/search/IvanMoch

### modify user information

PATCH http://Localhost:3000/api/user/IvanMoch


### log user

POST http://Localhost:3000/api/user/logIn
Content-Type: application/json

{
    "username" : "IvanMoch",
    "password" : "IvanMoch"
}

### log out user
GET http://localhost:3000/api/user/logOut

### Create room

POST http://localhost:3000/api/room/create
Content-Type: application/json

{
    "name": "Chill Zone",
    "private": 0,
    "description": "A place to relax and unwind.",
    "likes": 120
}


### Get room information

GET http://localhost:3000/api/room/search/the%20room

### send message

POST http://localhost:3000/api/room/senMessage
Content-Type: application/json

{
    "user_id" : "c329ec2f-bb59-11ef-8a34-900f0c400779",
    "content" : "Message number 2",
    "room_id" : "3f8c3a3a-bd67-11ef-908c-900f0c400779"    
}

### Get all the messages of a room

GET http://localhost:3000/api/room/getMessages/the%20room

### Get the favorites rooms

GET http://localhost:3000/api/room/favoritesRooms/c329ec2f-bb59-11ef-8a34-900f0c400779

### Add new favorite

POST http://localhost:3000/api/room/addFavorite
Content-Type: application/json

{
    "roomID": "29154593-c1a4-11ef-a3fc-900f0c400779",
    "userID": "c329ec2f-bb59-11ef-8a34-900f0c400770"
}

### Get suggested rooms

GET http://localhost:3000/api/room/suggestedRooms